#!/usr/bin/env bash

# Update Conda environment with runtime dependencies
# echo "Updating Conda environment..."
# conda env update --file runtime.yml || { echo "Conda env update failed"; exit 1; }

# # Install additional runtime pip dependencies
# echo "Installing pip dependencies..."
# pip install -r requirements.txt
# pip install jupyter

echo "Starting pgcontents initialization"
echo "DATABASE_URL is $DATABASE_URL"
pgcontents init --no-prompt -l $DATABASE_URL || exit 1
# currently facing a known issue: https://github.com/quantopian/pgcontents/issues/80
# need to modify this file, lol: /app/.conda/lib/python3.8/site-packages/pgcontents/alembic/versions/2d46c89138b0_.py

echo "pgcontents initialized"

echo "Installing Jupyter extensions"
jupyter contrib nbextension install --user
echo "Extensions installed"

echo "Enabling nbextensions configurator"
jupyter nbextensions_configurator enable --user
echo "Nbextensions configurator enabled"

echo "Starting Jupyter Notebook"
jupyter notebook \
    --no-browser --no-mathjax --ip=0.0.0.0 --port=$PORT \
    $JUPYTER_NOTEBOOK_ARGS \
    notebooks
