#!/usr/bin/env bash

pgcontents init -l $DATABASE_URL --no-prompt || exit 1

jupyter contrib nbextension install --user
jupyter nbextensions_configurator enable --user

jupyter notebook \
    --no-browser --no-mathjax --ip=0.0.0.0 --port=$PORT \
    $JUPYTER_NOTEBOOK_ARGS \
    notebooks