#!/usr/bin/env bash

# Update Conda environment with runtime dependencies
echo "Updating Conda environment..."
conda env update --file runtime.yml || { echo "Conda env update failed"; exit 1; }

# Install additional runtime pip dependencies
echo "Installing pip dependencies..."
pip install -r requirements.txt

echo "Starting pgcontents initialization"
pgcontents init -l $DATABASE_URL --no-prompt || exit 1
echo "pgcontents initialized"

echo "Installing Jupyter extensions"
jupyter contrib nbextension install --user
echo "Extensions installed"

echo "Enabling nbextensions configurator"
jupyter nbextensions_configurator enable --user
echo "Nbextensions configurator enabled"

echo "Starting Jupyter Notebook"
jupyter notebook \
    --no-browser --no-mathjax --ip=0.0.0.0 --port=$PORT \
    $JUPYTER_NOTEBOOK_ARGS \
    notebooks
